version: '3'

services:
  web:
    build: .
#    command: python manage.py run -h 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/hygge/backend/services/web/project
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/val/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hygge_db
    ports:
      - 5432:5432


volumes:
  postgres_data: