version: "3"

services:
  web:
    build: ./hygge/crudpackage
    commend: python app.py run -h 0.0.0.0
    volumes:
      - ./hygge/crudpackage/:/hygge/backend
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
