version: '3'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/hygge/backend/services/web/project
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/val/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hygge_db


volumes:
  postgres_data: